{% set name = "lazytransform" %}
{% set version = "1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lazytransform-{{ version }}.tar.gz
  sha256: f3ef534bfca70961674891221fa8aa0c344c5953b46ca6688f46f19c1e8bbf92

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - category_encoders >=2.6.2
    - lightgbm >=3.2.1
    - matplotlib-base >=3.4.2
    - numpy <2.0
    - pandas >=1.2.4
    - python-dateutil >=2.8.1
    - scikit-learn >=1.2.2
    - scipy
    - tqdm >=4.61.1
    - xgboost >=1.6

test:
  imports:
    - lazytransform
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AutoViML/lazytransform
  summary: Clean your data using a scikit-learn transformer in a single line of code
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Automatically transform all categorical, date-time, NLP variables in your data set 
    to numeric in a single line of code for any data set any size.

extra:
  recipe-maintainers:
    - sugatoray
    - mfansler
    - AutoViML
