{% set name = "lazytransform" %}
{% set version = "1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lazytransform-{{ version }}.tar.gz
  sha256: f2036c9726ec0310dab2a4d6776ec295bebc86b70a0bb83a024bc1b4f87adf4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - category_encoders >=2.6.2
    - lightgbm >=3.2.1
    - matplotlib-base >=3.4.2
    - numpy >=1.20.3
    - pandas >=1.2.4,<2.0
    - python-dateutil >=2.8.1
    - scikit-learn >=0.24.2,<=1.2.2
    - scipy <1.11.0
    - tqdm >=4.61.1

test:
  imports:
    - lazytransform
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AutoViML/lazytransform
  summary: Clean your data using a scikit-learn transformer in a single line of code
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Automatically transform all categorical, date-time, NLP variables in your data set 
    to numeric in a single line of code for any data set any size.

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainer(s) from upstream package repo
    - AutoViML
    - mfansler
